[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
tic_tac_toe = "GCKtWv1LoV25cvabAGULqGk5e1aZpFDEZhbEX5JqdovU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
